version : '3'
services : 
  web : 
    build : ./testing
    ports : 
      - "8081:80"
    volumes : 
      - ./testing/code:/var/www/html
  backend :
    build : ./backend
    ports : 
      - "8080:8080"
    entrypoint : tail -f /dev/null
